[package]
name = "circuits"
type = "bin"
authors = ["0xmad"]

[dependencies]
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
binary_merkle_root = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
